/*
** EPITECH PROJECT, 2024
** Rtype [WSL: Ubuntu]
** File description:
** ConstantECS
*/

#pragma once

#define BACKGROUND_IMAGE "client/sprites/flo.png"
#define DEATH_IMAGE "client/sprites/Boum.gif"

#define WINDOW_WIDTH 750
#define WINDOW_HEIGHT 500

#define SPAWN_RATE 200
#define FIRE_RATE_EN 0.005
#define FIRE_RATE_BOSS 0.01

// Enemy : Pata-Pata
#define PATAPATA_HEALTH 10
#define PATAPATA_WIDTH 33.0F
#define PATAPATA_HEIGHT 36.0F
#define PATAPATA_SPEED_VX -100.0F
#define PATAPATA_SPEED_VY 50.0F

// Enemy : Quoicoubax
#define QUOICOUBAX_HEALTH 10
#define QUOICOUBAX_WIDTH 33.0F
#define QUOICOUBAX_HEIGHT 36.0F
#define QUOICOUBAX_SPEED_VX -60.0F
#define QUOICOUBAX_SPEED_VY 0.0F
#define QUOICOUBAX_SWITCH_TIME 1.5F

// Enemy : Boss
#define BOSS_HEALTH 500
#define BOSS_WIDTH 121.0F
#define BOSS_HEIGHT 162.0F
#define BOSS_POS_X (WINDOW_WIDTH - BOSS_WIDTH - 10)
#define BOSS_POS_Y ((WINDOW_HEIGHT - BOSS_HEIGHT) / 2)
#define BOSS_WAIT 1000

// Booster : Wiper
#define WIPER_WIDTH 17.0F
#define WIPER_HEIGHT 17.0F
#define WIPER_SPEED_VX 0.0F
#define WIPER_SPEED_VY 0.0F
#define WIPER_SWITCH_TIME 1.5F
#define WIPER_RATE 750

// Player
#define PLAYER_SPEED 100.0F
#define PLAYER_WIDTH 33.0F
#define PLAYER_HEIGHT 15.0F
#define PLAYER_DEFAULT_X 0.0F
#define PLAYER_DEFAULT_Y 0.0F

// Player Projectile
#define PLAYER_FIRE_RATE_S 0.4F
#define PLAYER_POWER_MAX_TIME 2.0F

#define PLAYER_PROJECTILE_PERCENTAGE_1 0.2F
#define PLAYER_PROJECTILE_SPEED_1 300.0F
#define PLAYER_PROJECTILE_DAMAGE_1 10

#define PLAYER_PROJECTILE_PERCENTAGE_2 0.4F
#define PLAYER_PROJECTILE_SPEED_2 350.0F
#define PLAYER_PROJECTILE_DAMAGE_2 15

#define PLAYER_PROJECTILE_PERCENTAGE_3 0.6F
#define PLAYER_PROJECTILE_SPEED_3 400.0F
#define PLAYER_PROJECTILE_DAMAGE_3 30

#define PLAYER_PROJECTILE_PERCENTAGE_4 0.8F
#define PLAYER_PROJECTILE_SPEED_4 450.0F
#define PLAYER_PROJECTILE_DAMAGE_4 50

#define PLAYER_PROJECTILE_PERCENTAGE_5 0.99F
#define PLAYER_PROJECTILE_SPEED_5 500.0F
#define PLAYER_PROJECTILE_DAMAGE_5 75

#define PLAYER_PROJECTILE_SPEED_6 600.0F
#define PLAYER_PROJECTILE_DAMAGE_6 100

// ZIndex
#define PLAYER_ZINDEX 3
#define ENEMY_ZINDEX 3
#define PROJECTILE_ZINDEX 1
#define BACKGROUND_ZINDEX 0
